spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      keySerializer: ${KAFKA_KEY_SERIALIZER}
      valueSerializer: ${KAFKA_VALUE_SERIALIZER}
server:
  port: 8081
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30