spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/department_manager
#    url: jdbc:postgresql://localhost:5439/department_manager
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      keySerializer: ${KAFKA_KEY_SERIALIZER}
      valueSerializer: ${KAFKA_VALUE_SERIALIZER}
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30